### PR TITLE
feat: allow double and float

### PR DESCRIPTION
**Pull request by joscha**
This allows simple logging of floats and doubles (printed precision is 2 decimals)

### CODE REVIEW

**Comment by wolfspyre** [comment]
Is this going to be merged and released?

**Comment by joscha** [comment]
That would be great - ping @thijse

**Comment by joscha** [comment]
@thijse any chance to add more collaborators to this repo instead?

**Comment by thijse** [comment]
I finally merged your suggestion. I would be happy to add you as collaborator!

**Comment by joscha** [comment]
@wolfspyre @hoblins @racer01 released in `1.0.2` via #3

**Comment by arandomliz** [comment]
Would it be possible to allow formatting of floats?

**Pull request merged**
